application: sybil
version: production
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# -------------------------------------
#      Files
# -------------------------------------
- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  script: sitemap.py

- url: /static_sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /src\.zip
  script: views/zipme.py


# -------------------------------------
#      Urls
# -------------------------------------
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin/__init__.py
  login: admin
  
- url: /create(?:(?:/)(?:.*)|(?:\b))
  script: controller.py
  login: required

- url: /custom(?:(?:/)(?:.*)|(?:\b))
  script: controller.py
  login: required
  
- url: /manage(?:(?:/)(?:.*)|(?:\b))
  script: controller.py
  login: required
  
- url: /world/(edit|delete|join|leave)/?
  script: controller.py
  login: required
  
- url: /.+/(edit|delete)/?
  script: controller.py
  login: required
  
- url: .*
  script: controller.py
  
# -------------------------------------
  
- url: /about(?:(?:/)(?:.*)|(?:\b))
  script: about.py

- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /contextfree(?:(?:/)(?:.*)|(?:\b))
  script: contextfree.py

- url: /create(?:(?:/)(?:.*)|(?:\b))
  script: new.py
  login: required

- url: /custom(?:(?:/)(?:.*)|(?:\b))
  script: custom.py
  login: required

- url: /discover(?:(?:/)(?:.*)|(?:\b))
  script: discover.py

- url: /first(?:(?:/)(?:.*)|(?:\b))
  script: firstvisit.py

- url: /manage(?:(?:/)(?:.*)|(?:\b))
  script: manage.py
  login: required

- url: /update.*
  script: update.py

- url: /update(?:(?:(?:/)(?:.*))+|(?:\b))
  script: update.py

- url: /world/(edit|delete|join|leave)/?
  script: worlds.py
  login: required

- url: /world(?:(?:/)(?:.*)|(?:\b))
  script: worlds.py

- url: /.+/(edit|delete)/?
  script: main.py
  login: required

- url: .*
  script: main.py
